disconnect_pin -inst mul8_0/test_A_reg_7_ -pin SI -net mul8_0/n99
disconnect_pin -inst mul8_0/test_A_reg_6_ -pin SI -net mul8_0/n100
disconnect_pin -inst mul8_0/test_A_reg_5_ -pin SI -net mul8_0/n101
disconnect_pin -inst mul8_0/test_A_reg_4_ -pin SI -net mul8_0/n102
disconnect_pin -inst mul8_0/test_B_reg_1_ -pin SI -net mul8_0/n97
disconnect_pin -inst mul8_0/test_B_reg_0_ -pin SI -net mul8_0/n98
disconnect_pin -inst mul8_0/test_A_reg_3_ -pin SI -net mul8_0/n28
disconnect_pin -inst mul8_0/test_B_reg_2_ -pin SI -net mul8_0/n96
disconnect_pin -inst mul8_0/test_B_reg_7_ -pin SI -net mul8_0/n31
disconnect_pin -inst mul8_0/test_A_reg_2_ -pin SI -net mul8_0/n33
disconnect_pin -inst mul8_0/test_B_reg_5_ -pin SI -net mul8_0/n27
disconnect_pin -inst mul8_0/test_B_reg_3_ -pin SI -net mul8_0/net1768
disconnect_pin -inst mul8_0/test_B_reg_6_ -pin SI -net mul8_0/net1888
disconnect_pin -inst mul8_0/test_B_reg_4_ -pin SI -net mul8_0/n30
disconnect_pin -inst mul8_0/test_A_reg_1_ -pin SI -net mul8_0/net1785
disconnect_pin -inst mul8_0/test_A_reg_0_ -pin SI -net {S[14]}
disconnect_pin -inst mul8_0/S_reg_0_ -pin SI -net digi_out
disconnect_pin -inst mul8_0/S_reg_6_ -pin SI -net {S[5]}
disconnect_pin -inst mul8_0/S_reg_5_ -pin SI -net {S[4]}
disconnect_pin -inst mul8_0/S_reg_3_ -pin SI -net {S[2]}
disconnect_pin -inst mul8_0/S_reg_4_ -pin SI -net {S[3]}
disconnect_pin -inst mul8_0/S_reg_2_ -pin SI -net {S[1]}
disconnect_pin -inst mul8_0/S_reg_13_ -pin SI -net {S[12]}
disconnect_pin -inst mul8_0/S_reg_12_ -pin SI -net {S[11]}
disconnect_pin -inst mul8_0/S_reg_9_ -pin SI -net {S[8]}
disconnect_pin -inst mul8_0/S_reg_1_ -pin SI -net {S[0]}
disconnect_pin -inst mul8_0/S_reg_10_ -pin SI -net {S[9]}
disconnect_pin -inst mul8_0/S_reg_8_ -pin SI -net {S[7]}
disconnect_pin -inst mul8_0/S_reg_7_ -pin SI -net {S[6]}
disconnect_pin -inst mul8_0/S_reg_11_ -pin SI -net {S[10]}
disconnect_pin -inst mul8_0/S_reg_14_ -pin SI -net {S[13]}
disconnect_pin -inst mul8_0/S_reg_15_ -pin SI -net mul8_0/n26
